# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IPHONE_SIMULATOR: "platform=iOS Simulator,name=iPhone 11"
  IPAD_SIMULATOR: "platform=iOS Simulator,name=iPad Air (4th generation)"

jobs:
  build_test_iphone:
    runs-on: macos-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: build app and test
        run: xcodebuild -quiet -scheme inspire -configuration Debug -destination "$IPHONE_SIMULATOR" test

  build_test_ipad:
    runs-on: macos-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: testing
        run: xcodebuild -quiet -scheme inspire -configuration Debug -destination "$IPAD_SIMULATOR" test
